apiVersion: v1
kind: Service
metadata:
  name: dih-postgres
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
    name: postgres
  clusterIP: None # Makes it "Headless" (Internal Only)
  selector:
    app: postgres